# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0007_geobucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
