# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_auto_20160310_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
