# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0010_auto_20160316_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='instructions',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
