# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 19:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0011_auto_20160329_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='sv_location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
